# 基本信息  
title: "Microflow Documentation"  
description: "Your gateway to Microflow knowledge."  
baseurl: "" # 如果部署在子目录，例如 "/docs"，这里设置子目录路径  
url: "https://Microflow-IO.github.io"  

# 使用 Just the Docs 主题  
remote_theme: just-the-docs/just-the-docs  
search_enabled: true  # 启用搜索功能  

# 自定义 CSS 样式  
css:  
  - assets/css/custom.css

just_the_docs:  
  # 左侧导航设置  
  collapse_navigation: true  
  default_layout: "default"  
  aux_links:  
    "GitHub Repository":  
      - url: "https://github.com/Microflow-IO/Microflow-IO.github.io"  
      - external: true  
  search:  
    button: true  # 显示顶部搜索按钮  

# 导航顺序  
defaults:  
  - scope:  
      path: ""  
    values:  
      layout: "default"  
      nav_order: 1  
      toc: true # 启用右侧目录
