# 网站基本信息  
title: "Microflow Documentation"  
description: "Your gateway to Microflow knowledge."  
baseurl: "" #不在子路径下保持空  
url: "https://Microflow-IO.github.io"  

# 使用 Just the Docs 主题  
remote_theme: just-the-docs/just-the-docs  
search_enabled: true  

# 左侧菜单功能设置  
just_the_docs:  
  logo: "/assets/images/logo.png" # 如果需要自定义 logo  
  aux_links: # 顶部附加链接  
    "GitHub Repository":  
      - url: "https://github.com/Microflow-IO/Microflow-IO.github.io"  
      - external: true  
  collapse_navigation: true  
  default_layout: default  
  search:  
    button: true  

# TOC 右侧目录全局功能  
defaults:  
  - scope:  
      path: "" # 作用于所有文档  
    values:  
      layout: default  
      nav_order: 1  
      toc: true # 启用右侧目录  

# 文件结构定义  
collections:  
  docs:  
    output: true # 生成 HTML  
    permalink: /:collection/:path/
