# 基本信息  
title: "Microflow Documentation"  
description: "Your gateway to Microflow knowledge."  
baseurl: "" # 如果部署在子目录，例如 "/docs"，这里设置子目录路径  
url: "https://Microflow-IO.github.io"  

# Logo file path  
logo: "/assets/github_microflow_B.png"  

# 使用 Just the Docs 主题  
remote_theme: just-the-docs/just-the-docs  
search_enabled: true  # 启用搜索功能  

# 自定义 CSS 样式  
css:  
  - assets/css/custom.css

just_the_docs:  
  # 左侧导航设置  
  collapse_navigation: true # 允许菜单项折叠  
  default_layout: "default"  
  aux_links:  
    "GitHub Repository":  
      - url: "https://github.com/Microflow-IO/Microflow-IO.github.io"  
      - external: true  
  # 自定义菜单  
  navigation_label: "Documentation" # 左上角导航标题  
  collection_name: "docs" # 确保文档集合被识别

# 导航顺序  
defaults:  
  - scope:  
      path: ""  
    values:  
      layout: "default"  
      nav_order: 1  
      toc: true # 启用右侧目录

# Enable mermaid support  
mermaid:  
  # Version of mermaid library  
  version: "9.1.3"  
  # Setting this to true will load the Mermaid JS library  
  enable: true   
  # Remove this line if you want to use the default theme  
  # theme: "dark"
